---
- name: Update cache
  ansible.builtin.apt:
    update_cache: true
  changed_when: false

- name: Install common packages
  ansible.builtin.package:
    name:
      - wget
      - nano
      - vim
      - htop
      - curl
      - iftop
      - sysstat
      - net-tools
      - telnet
      - unzip
      - screen
      - git
      - ca-certificates
    state: present
