---
- name: Enable amnezia repositories
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    state: present
    update_cache: true
  loop:
    - repo: deb https://ppa.launchpadcontent.net/amnezia/ppa/ubuntu {{ ansible_distribution_release }} main
    - repo: deb-src https://ppa.launchpadcontent.net/amnezia/ppa/ubuntu {{ ansible_distribution_release }} main

- name: Install prerequesties
  ansible.builtin.apt:
    name:
      - software-properties-common
      - python3-launchpadlib
      - gnupg2
      - wireguard-tools
      - amneziawg
      - resolvconf
    state: present

- name: Ensure net.ipv4.ip_forward is enabled
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: true

- name: Copy file awg.conf
  ansible.builtin.copy:
    dest: /etc/amnezia/amneziawg/awg.conf
    content: "{{ vault_awg_content }}"
    owner: root
    group: root
    mode: '0600'
  notify:
    - Restart awg interface

- name: Check if awg interface exists
  ansible.builtin.command: ip link show awg
  register: awg_interface
  ignore_errors: true
  changed_when: false

- name: Enable awg-quick@awg service
  ansible.builtin.systemd:
    name: awg-quick@awg
    enabled: true
    state: started
  when: awg_interface.failed

- name: Create WireGuard configuration directory
  ansible.builtin.file:
    path: "/etc/wireguard"
    state: directory
    mode: '0755'

- name: Copy file wg0.conf
  ansible.builtin.copy:
    dest: /etc/wireguard/wg0.conf
    content: "{{ vault_wg_content }}"
    owner: root
    group: root
    mode: '0600'
  notify:
    - Restart wg0 interface

- name: Check if wg0 interface exists
  ansible.builtin.command: ip link show wg0
  register: wg_interface
  ignore_errors: true
  changed_when: false

- name: Enable wg-quick@wg0 service
  ansible.builtin.systemd:
    name: wg-quick@wg0
    enabled: true
    state: started
  when: wg_interface.failed
