---
- name: Set fact for MacOS
  ansible.builtin.set_fact:
    user_name: "{{ vault_macos_user }}"
  when: ansible_os_family == "Darwin"

- name: Set fact for Ubuntu
  ansible.builtin.set_fact:
    user_name: "root"
  when: ansible_os_family == "Debian"

- name: Add authorized keys
  ansible.posix.authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ item.key }}"
    follow: true
  when: '"all" in item.servers or inventory_hostname in item.servers'
  loop: "{{ add_root_ssh_keys }}"

- name: Delete old ssh-keys
  ansible.posix.authorized_key:
    user: "{{ user_name }}"
    key: "{{ item }}"
    state: absent
    follow: true
  loop: "{{ delete_root_ssh_keys }}"
