---
- name: Add authorized keys for root
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ item.key }}"
    follow: true
  when: '"all" in item.servers or inventory_hostname in item.servers'
  loop: "{{ add_root_ssh_keys }}"

- name: Delete old ssh-keys
  ansible.posix.authorized_key:
    user: root
    key: "{{ item }}"
    state: absent
    follow: true
  loop: "{{ delete_root_ssh_keys }}"
