---
- name: Create node_exporter user
  ansible.builtin.user:
    name: "{{ linux_node_exporter_user }}"
    create_home: false
    shell: /usr/sbin/nologin
    comment: node_exporter service user

- name: Create node_exporter archive folder
  ansible.builtin.file:
    path: /opt/node_exporter
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Download and unzip node_exporter
  ansible.builtin.unarchive:
    src: "{{ linux_node_exporter_source_url }}"
    dest: /opt/node_exporter
    remote_src: true
    mode: "0644"
    owner: root

- name: Copy node-exporter binary to the bin folder
  ansible.builtin.copy:
    src: /opt/node_exporter/node_exporter-{{ linux_node_exporter_version }}.linux-amd64/node_exporter
    dest: "{{ linux_node_exporter_bin }}"
    owner: "{{ linux_node_exporter_user }}"
    group: "{{ linux_node_exporter_user }}"
    mode: "0755"
    remote_src: true

- name: Copy node-exporter service
  ansible.builtin.template:
    src: etc/systemd/system/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: "0755"
  notify:
    - Systemctl daemon-reload node-exporter
    - Restart node_exporter service

- name: Enable node_exporter systemd unit
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: true
