---
- name: Install required system packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - software-properties-common
    state: present
    update_cache: true

- name: Add Docker`s official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    update_cache: true

- name: Install Docker Engine
  ansible.builtin.apt:
    name: docker-ce
    state: present

- name: Install Docker Compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v{{ docker_install_compose_version }}/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  notify:
    - Restart Docker

- name: Ensure Docker service is started and enabled
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
